### ISSUE TITLE
Create URL routes

### ISSUE THREAD

**Issue by scott-coates** [Scott-Coates-Org/solo-project-multiplayer-trivia-emday4prez#24]
# Description
This app provides two main screens. **Screen A** is the "back-end" where you define categories, questions, and answers. **Screen B** is where users can play a game together in real time.

## Secret
**The secret is FUTURE_SUPER_HERO.** Give this to Moddy to finish setting up your project.

## Requirements
- [x] **Screen A:** Define the route `/manage`. This is "back-end" where you define categories, questions, and answers.
- [x] **Screen B:** Define the root route `/`. This is how users can play together.
- **Do NOT not create the UI layouts for either route, because that task will come next. For now, just ensure both routes take you to a blank screen.**
- **Do NOT not worry about auth or permissions in v1.**

**Comment by emday4prez** [comment]
created browser router and pushed to main branch
