### ISSUE TITLE
Run the app locally

### ISSUE THREAD

**Issue by scott-coates** [Scott-Coates-Org/solo-project-multiplayer-trivia-emday4prez#25]
# Description
Let's make sure you can run the app locally now. We will need to change our version of Node, install our app dependencies, and grab the credentials from Firebase.

## Requirements
- [x] Install Node.js ^16.10.
  - [x] [Windows](https://github.com/coreybutler/nvm-windows)
  - [x] [Mac](https://github.com/tj/n) 
- [x] We are using "yarn" instead of "npm" in this project. To install yarn, run: `npm install -g yarn`.
- [x] Install the dependencies, run: `yarn install`.
- [x] Get your Firebase config ids
  - [x]  Click `Project Overview` -> `Project settings`
![image](https://user-images.githubusercontent.com/1829591/210919423-24febb31-70cc-4258-8f98-ba3840aedf39.png)
  - [x] Scroll down to retrieve your credentials
![image](https://user-images.githubusercontent.com/1829591/210919630-9b0012db-923d-44fd-ae73-8ffcb3fcacc9.png)
- [x] Make a copy of .env.local.example and rename it to .env.local. Paste in your Firebase credentials.
- [x] Boot the local server, run `yarn start`. Make sure you can see this page at http://localhost:3000.
![image](https://user-images.githubusercontent.com/1829591/207774279-b251953b-5e62-4ca0-9324-9095c33bb238.png)

**Comment by emday4prez** [comment]
successfully started app development on port 3000
