### ISSUE TITLE
Configure Firebase

### ISSUE THREAD

**Issue by scott-coates** [Scott-Coates-Org/solo-project-multiplayer-trivia-emday4prez#26]
# Description
Firebase offers many different tools for developers, including file storage, databases, etc. For this project, we'll use it for **hosing** our React app and **storing** data in a database. Before we can do any of that, we need to configure Firebase.

**Do NOT run `firebase deploy`. Deployment will be in a later task.**

## Requirements
- [x] Login or create an account on Firebase: https://console.firebase.google.com/.
- [x] Once you're logged in, click "Add projecct" on the dashboard.
![image](https://user-images.githubusercontent.com/1829591/207709587-d153e946-f03e-4018-b8ad-aeae5a8287e1.png)
- [x] Give your project a name
![image](https://user-images.githubusercontent.com/1829591/207709738-ad0bb94a-0074-402d-87ad-25b025c136db.png)
- [x] **Uncheck** "Enable Google Analytics"
![image](https://user-images.githubusercontent.com/1829591/207709818-56ef6a58-b0a9-4e85-90e6-6b8db5d98420.png)
- [x] Create a web-pased app in your new project
![SMX_Spotify_Playlist_Maker_-_Overview_-_Firebase_console](https://user-images.githubusercontent.com/1829591/207710182-7f706284-ed73-421f-aff6-5ad7aacca3a6.png)
- [x] Configure your web-based app to allow hosting
![SMX_Spotify_Playlist_Maker_-_Add_app_-_Firebase_console](https://user-images.githubusercontent.com/1829591/207710621-03875287-2cae-476c-8a01-9b7ed202948b.png)
- [x] Copy your API Key and Project ID
![SMX_Spotify_Playlist_Maker_-_Add_app_-_Firebase_console](https://user-images.githubusercontent.com/1829591/207711088-37522cf7-652c-4615-9c81-3998985da55c.png)
- [x] Enable Firestore
![image](https://user-images.githubusercontent.com/1829591/210918301-4c700ed8-cf67-4290-9a9d-c3f50a470c22.png)
![image](https://user-images.githubusercontent.com/1829591/210918196-e750d1dd-1d68-466d-bd1d-1ad6017f90b8.png)
- [x] Enable Test Mode
![image](https://user-images.githubusercontent.com/1829591/210918401-bb412b1a-e8cc-457d-b188-9b842db0a355.png)
- [x] Leave defaults and complete setup wizard
![image](https://user-images.githubusercontent.com/1829591/210918445-44c05411-ff86-44ee-934d-44cfd68102dd.png)

- **Do NOT run `firebase deploy`. Deployment will be in a later task.**

**Comment by emday4prez** [comment]
completed all tasks
