### ISSUE TITLE
Handle /join route

### ISSUE THREAD

**Issue by scott-coates** [Scott-Coates-Org/solo-project-multiplayer-trivia-emday4prez#9]
# Description
After the user goes to the `/join` route, they will be presented with the `username` component that you created in a previous step. After they fill that in, they will be presented with the `join` component. This `join` component contains a text box where the player can enter in a room code. If the code is valid, the player will be brought to the lobby

![image](https://user-images.githubusercontent.com/1829591/211444360-6c776cbe-c52e-4845-9392-396184ad4405.png)

## Requirements
- [x] Display the `username` component when a player navigates to the `/join` route.
- [x] Remember, a valid username requires at least 2 characters.
- [x] Create a `join` component. Display this after the player provides their username (except for the game creator, they will go straight to the lobby).
- [x] When a player enters a valid room code, they will enter the lobby. The `lobby` component should **NOT** allow regular players to modify the lobby, because only the game creator can make changes (e.g. picking a category or hitting the start button).

**Comment by emday4prez** [comment]
closed with pr 44
